# Package setup

The DESCRIPTION file is created using this code.

```{r package-setup, message=FALSE, results='hide'}
usethis::create_package(
  path = ".",
  fields = list(
    Package = params$package_name,
    Version = "0.0.0.9000",
    Title = "flowcut",
    Description = "Time-smooth mixture modeling for flow cytometry data.",
    `Authors@R` = person(
      given = "Sangwon",
      family = "Hyun",
      email = "sangwonh@ucsc.edu",
      role = c("aut", "cre")
      )
  )
)
usethis::use_mit_license(copyright_holder = "Sangwon Hyun")
```

The following is what will show up when someone types `package?flowcut` in
the console.

```{package_doc}
#' flowcut
#'
#' This package implements the `flowcut` method.
#' 
#' @docType package
```


This package will have some dependancies:

```{r dependencies, message = FALSE}
library(tidyverse)
##library(ggplot2)
##usethis::use_package("tidyverse", type = "depends") 
## usethis::use_package("ggplot2")
usethis::use_package("ggplot2", type = "depends")
usethis::use_package("MASS", type = "depends")
usethis::use_package("parallel", type = "depends")
usethis::use_package("Rfast", type = "depends")
usethis::use_package("mvnfast", type = "depends")
usethis::use_package("stats", type = "depends")
usethis::use_package("matrixsampling", type = "depends")
usethis::use_package("matrixNormal", type = "depends")
usethis::use_package("pgdraw", type = "depends")
usethis::use_package("tmvnsim", type = "depends")
usethis::use_pipe(export=TRUE)
```





<!-- library("tmvnsim") ## for tmvnsim -->
<!-- library("MASS") ## for mvrnorm -->
<!-- library("scatterplot3d") # for 3d plot  -->
<!-- library("RColorBrewer") ## distinct colors  -->
<!-- library("matrixsampling") ## r-inverse Wishart -->
<!-- library("matrixNormal") ## matrix normal random elements  -->
<!-- library("pgdraw") ## draw PG r.v.'s  -->
<!-- library("parallel") ## mc-mapply -->
<!-- library("svMisc") -->
<!-- library("mclust") ## for warm start  -->
<!-- library("plotly") -->
<!-- library("ggcorrplot") -->

<!-- library("Rfast") -->
<!-- library("Rfast2") -->
