---
title: "Creating the ``r params$package_name`` R package"
author: "Sheng Jiang, Sangwon Hyun"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
knit: litr::render
output: litr::litr_gitbook
params:
  package_name: "flowcut" # <-- change this to your package name
  package_parent_dir: "." # <-- relative to this file's location
documentclass: book
---

# Introduction

This package implements `flowcut`, a Bayesian mixture of experts model used for
censored data (specialized for ocean flow cytometry). The documentation and
package are both created using one simple command:

```{r render, eval = FALSE}
litr::render("index.Rmd", output_format = litr::litr_gitbook())
```


This line is purely for testing (to be deleted later!).

```{r, eval = FALSE}
litr::load_all("index.Rmd")##, output_format = litr::litr_gitbook())
my_load <- function(){
  litr::render("~/repos/flowcut/index.Rmd", output_format = litr::litr_gitbook(minimal_eval = TRUE))
  devtools::load_all("~/repos/flowcut/flowcut")
}
```


