datafile = "../data/test.jld2"
savepath = "../output/fit_test.jld2"
nsam = 10000
[hyper]
K = 2
# sigma1
a1 = 1
b1 = 1 
# sigma2 
a2 = 1
b2 = 1 
# mean GP 
al1 = 0.1
bl1 = 1
ae1 = 0.1
be1 = 1
al2 = 0.1
bl2 = 1
ae2 = 0.1
be2 = 1
# weight GP 
as1 = 0.1
bs1 = 1
ap1 = 0.1
bp1 = 1
as2 = 0.1
bs2 = 1
ap2 = 0.1
bp2 = 1