datafile = "../data/test5.jld2"
savepath = "../output/fit_test5.jld2"
nsam = 50000
[hyper]
K = 3
# sigma1
a1 = 1
b1 = 1 
# sigma2 
a2 = 1
b2 = 1 
# sigma3
a3 = 1
b3 = 1 
# mean GP 
al1 = 1
bl1 = 1
ae1 = 1
be1 = 1
al2 = 1
bl2 = 1
ae2 = 1
be2 = 1
al3 = 1
bl3 = 1
ae3 = 1
be3 = 1
# weight GP 
as1 = 1
bs1 = 1
ap1 = 1
bp1 = 1
as2 = 1
bs2 = 1
ap2 = 1
bp2 = 1